name: Build My Game APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Flet Swiftly
        run: |
          python -m pip install --upgrade pip
          python -m pip install "flet[cli]" --break-system-packages

      - name: Setup Android SDK Environment
        uses: android-actions/setup-android@v3

      - name: Build Final APK
        run: |
          flet build apk --no-config
          
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flet-app-apk
          path: build/apk/*.apk
